/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_1ea16583 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/pkosrhnduommnhncrdyw/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
declare const Deno: { env: { get: (key: string) => string | undefined } };
// @ts-expect-error - JSR specifier (Deno runtime)
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

// ──────────────────────────────────────────────────────────────────────────────
// NOTE: The autogenerated schema says the JSONB column is called "value",
//       but the actual Supabase table column is "data".
//       All references below use "data" to match the real DB schema.
// ──────────────────────────────────────────────────────────────────────────────
const COL = "data";   // ← 실제 컬럼명. "value" 오류 시 "data"로 변경함.

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_1ea16583").upsert({
    key,
    [COL]: value,
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_1ea16583")
    .select(COL)
    .eq("key", key)
    .maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.[COL];
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_1ea16583").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase
    .from("kv_store_1ea16583")
    .upsert(keys.map((k, i) => ({ key: k, [COL]: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_1ea16583")
    .select(COL)
    .in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d: any) => d[COL]) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_1ea16583").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_1ea16583")
    .select(`key, ${COL}`)
    .like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d: any) => d[COL]) ?? [];
};
